from yacs.config import CfgNode as CN

_C = CN()

""""======================================="""
_C.MODEL = CN()
_C.MODEL.NAME = "baseline"

""""======================================="""
_C.SOLVER = CN()
_C.SOLVER.MAX_ITER = 2000
_C.SOLVER.BASE_LR = 1e-2
_C.SOLVER.BIAS_LR_FACTOR = 2
_C.SOLVER.WEIGHT_DECAY = 5e-4
_C.SOLVER.WEIGHT_DECAY_BIAS = 0

_C.SOLVER.OPTIMIZER = CN()
_C.SOLVER.OPTIMIZER.TYPE = "adam" # "sgd"
_C.SOLVER.OPTIMIZER.MOMENTUM = 0.9

_C.SOLVER.SCHEDULER = CN()
_C.SOLVER.SCHEDULER.TYPE = "warmup_multi" # "multi", "plateau"
_C.SOLVER.SCHEDULER.MILESTONES = [1000, 1500]
_C.SOLVER.SCHEDULER.GAMMA = 0.1
_C.SOLVER.SCHEDULER.WARMUP_FACTOR = 1.0 / 3
_C.SOLVER.SCHEDULER.WARMUP_ITERS = 500
_C.SOLVER.SCHEDULER.WARMUP_METHOD = "linear"

""""======================================="""
_C.DATASET = CN()
_C.DATASET.TRAIN_BATCH_SIZE = 1024
_C.DATASET.TEST_BATCH_SIZE = 1
_C.DATASET.TRAIN_NUM_WORKERS = 0
_C.DATASET.TEST_NUM_WORKERS = 4
_C.DATASET.LOGIT_ONLY = False
_C.DATASET.USE_GT_OBJ_TRAJS = False

""""======================================="""
_C.PREDICT = CN()
_C.PREDICT.OBJECT_NUM = 35
_C.PREDICT.PREDICATE_NUM = 132
_C.PREDICT.TOPK_PER_PAIR = 20
_C.PREDICT.TOPK_PER_SEG = 200
_C.PREDICT.FEATURE_DIM = 11070
# _C.PREDICT.TRIPLET_NUM = 2961

""""======================================="""
_C.RELPN = CN()
_C.RELPN.OBJECT_DIM = 1024

_C.RELPN.PPN = CN()
_C.RELPN.USE_PPN = True
_C.RELPN.PPN.NUM_PAIR_PROPOSALS = 256
_C.RELPN.PPN.IN_CHANNELS = 35 # OBJECT_NUM
_C.RELPN.PPN.HIDDEN_CHANNELS = 64
_C.RELPN.PPN.OUT_CHANNELS = 35 # OBJECT_NUM
_C.RELPN.PPN.BATCH_SIZE_PER_SEGMENT = 256
_C.RELPN.PPN.POSITIVE_FRACTION = 0.5

_C.RELPN.DPN = CN()
_C.RELPN.USE_DPN = True
_C.RELPN.DPN.NUM_DURATION_PROPOSALS = 64
_C.RELPN.DPN.DPN_ONLY = False
_C.RELPN.DPN.IN_CHANNELS = 1024
_C.RELPN.DPN.NUM_ANCHORS_PER_LOCATION = 4
_C.RELPN.DPN.ANCHOR_SIZES = 35
_C.RELPN.DPN.ANCHOR_STRIDE = 132

""""======================================="""
_C.ETC = CN()
_C.ETC.RANDOM_SEED = 0
_C.ETC.DISPLAY_FREQ = 1
_C.ETC.SAVE_FREQ = 20
_C.ETC.MODEL_DUMP_FILE = "baseline_weights_epoch_100.pt"