MODEL:
  NAME: "baseline"
SOLVER:
  MAX_ITER: 2000
  BASE_LR: 1e-2
  OPTIMIZER:
    TYPE: "adam"
  SCHEDULER:
    TYPE: "warmup_multi"
DATASET:
  TRAIN_BATCH_SIZE: 1
  TEST_BATCH_SIZE: 1
  LOGIT_ONLY: True
  USE_GT_OBJ_TRAJS: False
RELPN:
  USE_PPN: False
  USE_DPN: False
  PPN:
    BATCH_SIZE_PER_SEGMENT: 256
    POSITIVE_FRACTION: 0.25
    NUM_PAIR_PROPOSALS: 256
  DPN:
    NUM_DURATION_PROPOSALS: 64
ETC:
  RANDOM_SEED: 0
  DISPLAY_FREQ: 1
  SAVE_FREQ: 1000
  MODEL_DUMP_FILE: "baseline_weights_iter_2000.pt"